/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_immomo_connector_util_Coded */

#ifndef _Included_com_immomo_connector_util_Coded
#define _Included_com_immomo_connector_util_Coded
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_immomo_connector_util_Coded
 * Method:    clientSecretGen
 * Signature: ([B[BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_immomo_connector_util_Coded_clientSecretGen
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_immomo_connector_util_Coded
 * Method:    serverSecretGen
 * Signature: ([B[BII)I
 */
JNIEXPORT jint JNICALL Java_com_immomo_connector_util_Coded_serverSecretGen
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_immomo_connector_util_Coded
 * Method:    aesEncode
 * Signature: ([BI[BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_immomo_connector_util_Coded_aesEncode
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_immomo_connector_util_Coded
 * Method:    aesDecode
 * Signature: ([BI[BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_immomo_connector_util_Coded_aesDecode
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_immomo_connector_util_Coded
 * Method:    computeOutputLength
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_immomo_connector_util_Coded_computeOutputLength
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
